base_url = "https://alephcubed.com"
title = "AlephCubed"
description = "My work-in-progress personal website."

compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "material-dark"
external_links_target_blank = true
bottom_footnotes = true
insert_anchor_links = "left"

[extra]
default_description = "My work-in-progress personal website."
