base_url = "https://alephcubed.com"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
external_links_target_blank = true
bottom_footnotes = true
# insert_anchor_links = "left"

[extra]
# Put all your custom variables here
