[build]
target = "index.html"
dist = "dist"
release = false

[watch]
watch = ["./index.html", "src/", "static/", "css/"]

[clean]
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "sh"
# run tailwind build with webpack
command_arguments = [
  "-c",
  "[ ! -d \"./node_modules\" ] && npm i || :; npm run build_css",
]
